name: flutter_conf_latam_demo
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
  user_repository: 
    path: packages/user_repository
  user_repository_macros: 
    path: packages/user_repository_macros
  json: ^0.20.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0